# Generated by Django 5.2.13 on 2026-05-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_cars_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='name',
            new_name='car_name',
        ),
        migrations.AlterField(
            model_name='cars',
            name='speed',
            field=models.IntegerField(default=50),
        ),
    ]
